apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: nginx-service
spec:
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name: web-ingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: nginx-service
          servicePort: 8000
